### ISSUE TITLE
What to require

### ISSUE THREAD

**Issue by ziziermao** [ShinyChang/React-Text-Truncate#10]
Hey,
May I ask what to require when I try to use the TextTruncate?
I tried 
require('react-text-truncate');
require('react-text-truncate/TextTruncate');
require('react-text-truncate').TextTruncate;
all not working. Could you please suggest?

**Comment by ShinyChang** [comment]
I think it will work.

```
var TextTruncate = require('react-text-truncate').default;
```

Usually I used like this

```
import TextTruncate from 'react-text-truncate';
```

try it! 

Please reply me if you have any problem :)

**Comment by ziziermao** [comment]
thanks, this works!

**Comment by ShinyChang** [comment]
next version will fix this issue

and require will be

```
var TextTruncate = require('react-text-truncate');
```
