### ISSUE TITLE
Truncate char is going to the (n + 1)th line

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [ShinyChang/React-Text-Truncate#18]
Doesn't matter how many lines I configure it, the `…` char is always on the (n+1)th line. Don't really know how to debug, could you help me on that, please?

Screenshots:
![image](https://cloud.githubusercontent.com/assets/7771484/14177011/8cf80918-f72a-11e5-9261-953af2178dc1.png)
![image](https://cloud.githubusercontent.com/assets/7771484/14177026/af9f753c-f72a-11e5-992c-c0c20dffa51b.png)

**Comment by gabrielpugliese-luizalabs** [comment]
The CSS on the parent div is this:
```sass
    width: 346px;
    float: left;
    margin-right: 20px;
```

**Comment by ShinyChang** [comment]
Confirmed. The float element `<img/>` cause calculate error.

**Comment by gabrielpugliese-luizalabs** [comment]
Woo, thanks!
