### ISSUE TITLE
Incorrect truncating

### ISSUE THREAD

**Issue by LKay** [ShinyChang/React-Text-Truncate#19]
Component doesn't work well with asian languages that don't use spaces such as Japanese, Chinese, Korean, Thai etc. 

When text in these languages is mixed with some latin text with spaces, which is common to include foreign names text is being truncated after the first space even if some more text might fit in. When there are not spaces the text is being truncated just fine.

For example the text `SEO担当者であれば、検索順位のチェックは毎日行っていると思います。しかし、検索結果画面（SERPs）の内容までは、日々忙しいマーケッターやWebサイト管理者は、なかなかチェックができていないのではないでしょうか？` is being correctly truncated to `SEO担当者であれば、検索順位のチェックは毎日行っていると思います。しかし、検索結果画面（SERPs）の内容...`

But the text that contains space `Tool SEOは、日々忙しいマーケッターやWebサイト運用者にとって、SEO業務を限りなく効率的に行えるようにしていきたいと考えています。` is being truncated to just `Tool...`

**Comment by ShinyChang** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/1590707/14248416/207a3a42-faa7-11e5-81bd-6895e316890d.png)
