### ISSUE TITLE
global.react is undefined

### ISSUE THREAD

**Issue by jasonenglish** [ShinyChang/React-Text-Truncate#22]
When lib/index.js is loaded in a browser, it's unable to find [global.react](https://github.com/ShinyChang/React-Text-Truncate/blob/c65c134b095bf21064c2a5b71c0f76de2c4db3f3/lib/index.js#L10). Shouldn't it be global.React? Looking at Reacts documentation and their [jsfiddle](https://jsfiddle.net/reactjs/69z2wepo/) example, I see that it's available under `window.React` not `window.react`

Thoughts?

Thanks!

**Comment by ShinyChang** [comment]
Confirmed. Dunno why babel transform incorrect.

**Comment by ShinyChang** [comment]
Hi @jasonenglish ,
I fixed this problem. You can checkout the newest version :D

**Comment by jasonenglish** [comment]
Awesome, thanks!
