### ISSUE TITLE
textTruncateChild is optional but checks only for textTruncateChild.type === 'string'

### ISSUE THREAD

**Issue by vasyanik** [ShinyChang/React-Text-Truncate#30]
It's breaks use without textTruncateChild :(

**Comment by ShinyChang** [comment]
Oops! My fault, will fix it soon.

Vasiliy Nikolaev <notifications@github.com> 於 2016年7月6日 週三 下午8:04 寫道：

**Comment by ShinyChang** [comment]
@vasyanik , fixed. Released new version also.

**Comment by vasyanik** [comment]
@ShinyChang thanks, man
