### ISSUE TITLE
startPos gets equal to maxTextLength wrong way

### ISSUE THREAD

**Issue by vasyanik** [ShinyChang/React-Text-Truncate#31]
It happens with long first words (when length is almost as long as width of container)
And outcome is that it won't truncate text - just will show it full.
Sorry, for no snippet for it - writing from phone now :)
Try please, for example, for container with fixed width and just put long word at start.
Thanks!

**Comment by ShinyChang** [comment]
Sorry, I can't reproduce it. But It can be fixed after #29 done, I think.

**Comment by vasyanik** [comment]
@ShinyChang could you please publish 0.8.2 to npm?

**Comment by ShinyChang** [comment]
Oops, I forgot it! Sorry again. Now published.
