### ISSUE TITLE
truncateText value not rendering properly 

### ISSUE THREAD

**Issue by reintroducing** [ShinyChang/React-Text-Truncate#34]
So this may be specific to how our staging server is set up but I noticed this ONLY when the site is deployed to our staging server.  Every instance of this module renders incorrectly: https://www.dropbox.com/s/ft6q4qf7o11brx7/Screenshot%202016-07-29%2006.47.08.png?dl=0

As you can see, the `...` is being rendered as weird characters at the end of every string. I have a feeling this is due to the fact that the `truncateText` defaults to the three dots but they aren't actual periods rather the three dot character (whatever thats called). I imagine this is an encoding issue somewhere along the line and will render incorrectly like it is on my server depending on server settings perhaps? It might be worth setting the default to be the actual three dots or allow a global truncateText setting so that a user can set it once and not have to worry about this happening everywhere.

**Comment by ShinyChang** [comment]
I'm not sure what's going on. Did you check the HTML source of staging server responded? Any characters shown before `<doctype html>`? And `<meta charset="utf-8">` in the `<head>`?

**Comment by reintroducing** [comment]
I'm at a cabin this weekend for a little getaway with my family and don't have my machine. Will get back to you Monday morning on this, thanks.

**Comment by ShinyChang** [comment]
Have a nice weekend! 😀

Matt Przybylski <notifications@github.com> 於 2016年7月30日 週六 下午8:46 寫道：

**Comment by reintroducing** [comment]
Hmm, nothing before the doctype and the charset is correctly set to utf-8.  I will double check with our server admins to see if anything is set up incorrectly there but I can't really think of what may be causing this.

**Comment by reintroducing** [comment]
This is definitely something with our servers, on my personal site's server I'm seeing it correctly. Apologies for the noise, will get it figured out with our devops team.

**Comment by ShinyChang** [comment]
Maybe you can try `中文` in the staging server, it will be rendered incorrect if html file encoding is not UTF-8. Hope this can help you. :)

**Comment by reintroducing** [comment]
The encoding was set to ISO something a rather on the server in error, its now set to UTF-8 and all is well :)  Thanks again.
