### ISSUE TITLE
error forceUpdate while resizing.

### ISSUE THREAD

**Issue by davelab** [ShinyChang/React-Text-Truncate#37]
Hi I get this warning message when i resize the browser window:

`Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the TextTruncate component.`

I saw that you listen the resize window event to foce the render. I don't understand why.

**Comment by ShinyChang** [comment]
Hi @davelab,

This component may be used in fluid layout. It will be broken if no re-calculator the width of container when mobile device orientation changed.

But I can not reproduce your problem, could you give me a mvp to reproduce it?
