### ISSUE TITLE
question about line-clamp, ellipses only

### ISSUE THREAD

**Issue by rt2zz** [ShinyChang/React-Text-Truncate#40]
thanks for the great lib. I have a need to make a few changes:
- use webkit-line-clamp css in webkit (this means ellipsis only)
- remove onresize listeners (perf)

you can see my fork here: https://github.com/rt2zz/React-Text-Truncate (sorry about the diff, I made some style tweaks along the way)

I think these changes are probably not general enough to be merged back here, both cut functionality to gain small perf benefits. But I thought I would bring it up here just in case. If some of these changes are desired I am happy to PR.

**Comment by ShinyChang** [comment]
Hi @rt2zz 

Sorry for late reply. Your fork is awesome, but I hope `react-text-truncate` is more flexible in this case. Please feel free to folk as other package and publish to npm or others.

**Comment by rt2zz** [comment]
👍 🎈
