### ISSUE TITLE
Allow to choose the inner element for text

### ISSUE THREAD

**Issue by erasmo-marin** [ShinyChang/React-Text-Truncate#46]
Hi, first of all, great work.
This is more like a feature request. I think that would be cool if you can set the inner element to use, like h1...h5, p, span or div, for example. This is useful when you already have global css styles for those elements.

ie: 

```jsx
<TextTruncate element="h1" text="hello world" line={1}/>
```

Is it possible?

**Comment by ShinyChang** [comment]
ok, will add this feature in next version
thanks @erasmo-marin
