### ISSUE TITLE
Text is not truncated right when the style property changes

### ISSUE THREAD

**Issue by erasmo-marin** [ShinyChang/React-Text-Truncate#49]
Text is not truncated right when the style property changes

I'm not sure, but I think the problem occurs because the canvas is created only on componentDidMount, so the width is not measured right if the style property or the css rules changes. Calling to the update method doesn't fix the problem. Removing the style property from the div in the web inspector shows that apparently the component is ignoring the style prop.

This is the rendered text (line prop set to 1):
![screenshot at may 29 12-12-35](https://cloud.githubusercontent.com/assets/8242873/26556503/d5d53412-4468-11e7-9b0f-840c4e49f644.png)

This is after removing the style prop:
![screenshot at may 29 12-13-26](https://cloud.githubusercontent.com/assets/8242873/26556506/d93b362e-4468-11e7-97e8-6afddd29e8c7.png)

I think a solution would be to recreate the canvas in every render. Of course there are performance concerns about this solution.

**Comment by StephenMayeux** [comment]
Thank you for creating a very nice and useful React component!

I am also having the same issue. I use `redux-responsive`,  and my client's height/width dimensions are available to my component as props (this.props.browser). For widths greater than 768px, I want my text to be 18px,  and for smaller widths I want the font-size to be 14px. So what I have is:
``` javascript
<h2
  style={{ fontSize: this.props.browser.lessThan.medium ? 14 : 18 }}
>
  <TextTruncate
     text={this.props.someText}
     line={2}
     ref="truncatedActivityTitle"
   />
</h2>
```
And if the user resizes the browser window, `redux-responsive` will send new props to my component and thus re-render. So I use this lifecycle method to call the `update()` method.

``` javascript
componentWillReceiveProps (nextProps) {
  if (this.props.browser.lessThan.medium !== nextProps.browser.lessThan.medium) {
    this.refs.truncatedActivityTitle.update()
  }
}
```
`componentWillReceiveProps` is getting called and my `font-size` changes, but the text is not truncated correctly. Any suggestions or fixes would be greatly appreciated. I re

**Comment by ShinyChang** [comment]
I will create a method to update the canvas property for workaround in next version.
You have to force update manually. Something like below:

```js
this.refs.truncatedTitle.updateCanvasProp();
```

**Comment by StephenMayeux** [comment]
I was able to make it work by adding `componentWillReceiveProps`, but I will also try your solution. Thank you again.

**Comment by ShinyChang** [comment]
I published new version 0.10.2 fixed this issue.
I updated the canvas property when called `update()`. I test it and it does not effected performance.

**Comment by erasmo-marin** [comment]
Great, working like a charm!! no performance issues I can notice

Thank you very much @ShinyChang

**Comment by erasmo-marin** [comment]
Hi again @ShinyChang ,

I have been testing and it's not working in all cases. It improved in some cases but not always. It is because the ref (this.scope) is not taking in consideration the inline styles.

If I access the component object from the react developers tools, the canvas property displays "16px ...." but I'm passing 35px in inline styles.

If you change the style property in the root element like this, to consider at least the font size from the inline style, it works a lot better:

`style: { overflow: 'hidden', fontSize: this.props.style.fontSize }`

So, the fix is to extract all the font related styles from the inline styles and pass them to the root element. That way, the canvas will take the right styles.
