### ISSUE TITLE
Internet Explorer renders both truncated and un-truncated text

### ISSUE THREAD

**Issue by jrabramson** [ShinyChang/React-Text-Truncate#56]
Hopefully this example is decent
![image](https://user-images.githubusercontent.com/6433887/30066381-b61879bc-9225-11e7-8699-a62c0a000d00.png)
Using recommended react, seeing this in all versions of IE up to 15

**Comment by ShinyChang** [comment]
I tested `v0.13.x` on IE 9 and it works fine (https://www.browserling.com/browse/win/vista/ie/9/https%3A%2F%2Fshinychang.net%2FReact-Text-Truncate%2F) so I will close this issue.
Please reopen the issue if you faced this issue again.
