### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by didi0613** [ShinyChang/React-Text-Truncate#59]
Hi,

Do you have any plans for upgrading to react 16?
Seeing issues when using React 16 in our app
```
npm WARN react-text-truncate@0.8.3 requires a peer of react-dom@^0.14.7 || ^15.0.0 but none was insta
lled.
```

**Comment by ShinyChang** [comment]
Yes, but not so quickly.

**Comment by kamronbatman** [comment]
I see support on this fork: [erasmo-marin/React-Text-Truncate](https://github.com/erasmo-marin/React-Text-Truncate)

@erasmo-marin - Would you be willing to do a PR?
