### ISSUE TITLE
Incorrect Truncate

### ISSUE THREAD

**Issue by brightsider** [ShinyChang/React-Text-Truncate#75]
Should Display rH2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8o… or rH2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8…
But displayed H2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8o..

![address](https://user-images.githubusercontent.com/4996231/55379836-f0e26d80-5526-11e9-931f-4cc274949089.png)

Full text is rH2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8orH2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8o

**Comment by ShinyChang** [comment]
Hi @brightsider ,
can you create a demo page for me?

**Comment by brightsider** [comment]
```
 render() {
        return (
            <div className='container'>
                <TextTruncate
                    line={1}
                    truncateText="…"
                    text={'rH2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8orH2ivGxNu5UX73rt76nLiCjtvwrtg4Tx8o'}
                    ref='idRef'
                    containerClassName='address'
                />
            </div>
        )
    }
```

```
.address {
    display: flex;
    width: calc((100% - 388px) / 2 - 48px);
    margin: 24px;
    font-family: 'AvenirNext-Medium';
    font-size: 14px;
    color: var(--main-text);
    justify-content: center;
}

.container {
    display: flex;
    flex: 1;
    flex-direction: column;
    height: 100%;
    position: relative;
    overflow-y: scroll;
    background-color: var(--background)
}
```

**Comment by ShinyChang** [comment]
Hi @brightsider , 
I cannot reproduce it, may I know which version you installed?
![image](https://user-images.githubusercontent.com/1590707/55685653-379ef000-598b-11e9-8e15-ff5f18caf6cf.png)

**Comment by brightsider** [comment]
@ShinyChang 0.14.0
React 16.8.6
I'm used Electron with React

**Comment by brightsider** [comment]
@ShinyChang try to resize window multiple times and it's should reproduce

**Comment by ShinyChang** [comment]
I guess this is because of the width is not an integer and browser truncate the latest pixel.

**Comment by brightsider** [comment]
How to fix it?

**Comment by ShinyChang** [comment]
![image](https://user-images.githubusercontent.com/1590707/55732932-74ccb600-5a4f-11e9-9bb6-d00e6c8e844e.png)
the dots only displays two dots when width is `306.2px`.

I have no idea how to fix it for now...

**Comment by brightsider** [comment]
If using integer width then issue should gone?

**Comment by ShinyChang** [comment]
As I know, yes.

**Comment by ShinyChang** [comment]
Please reopen if still have problem
