### ISSUE TITLE
Not work for flexbox

### ISSUE THREAD

**Issue by arthur791004** [ShinyChang/React-Text-Truncate#77]
## Description
When I want to truncate text with `flex: 1`, it doesn't work.

```jsx
// css
.wrapper {
  display: flex;
}

.truncate {
  flex: 1;
}

// html
<div className="wrapper">
  <div className="truncate">
    <TextTruncate line={2} text={long} />
  </div>
  <div className="rest">rest</div>
</div>
```

## Reproduce
https://codesandbox.io/s/92yrr9j3ly

**Comment by ShinyChang** [comment]
![2020-04-15 09 32 02](https://user-images.githubusercontent.com/1590707/79289523-0b9e3f00-7efc-11ea-8b8c-112b55ace80a.gif)

looks work fine, please reopen if still have problem.
