### ISSUE TITLE
Repository should reflect version update

### ISSUE THREAD

**Issue by Bertg** [ShinyChang/React-Text-Truncate#81]
Hi,

Last week you released 0.15.0 to NPM. This repository does not reflect that.
It's not visible in the commits, in the changelog or the releases.

As you know the NPM world has had it fair share of packages being hijacked, and this release rang a lot of alarm bells. Luckily there are tools like https://diff.intrinsic.com to put one at ease.

I strongly suggest to make sure that the repo reflects the latest release, at the bare minimum in the Changelog. 

Kind regards,

Bert Goethals

**Comment by ShinyChang** [comment]
Sorry, it's my bad. Just updated the changelog.
