### ISSUE TITLE
Loosen React version requirements in peer deps

### ISSUE THREAD

**Issue by jamos99** [ShinyChang/React-Text-Truncate#99]
Hey there,

We're seeing warnings due to React 17, anything preventing these requirements be expanded to include React 17?
https://github.com/ShinyChang/React-Text-Truncate/blob/master/package.json#L48-L51

Thanks!

**Comment by ShinyChang** [comment]
@jamos99 please install `0.17.0` which version should not have warnings. Let me know if still have problem.

**Comment by pmartin35** [comment]
@ShinyChang I see the React 17 changes were merged `master`. Any chance you could release this to npm?

**Comment by ShinyChang** [comment]
Hi @pmartin35 , I publish the new version to support React v18, you can check https://www.npmjs.com/package/react-text-truncate
